version: 1
formatters:
  brief:
    format: "%(asctime)s - %(message)s"
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s -%(lineno)d- %(message)s"
handlers:
  console:
    class : logging.StreamHandler
    formatter: brief
    level   : INFO
    stream  : ext://sys.stdout
  file:
    class : logging.handlers.TimedRotatingFileHandler
    formatter: simple
    level: DEBUG
    filename: info.log
    encoding: utf8
    when: S
    backupCount: 20
  error:
    class: logging.handlers.TimedRotatingFileHandler
    level: ERROR
    formatter: simple
    filename: error.log
    #maxBytes: 10485760
    backupCount: 20
    encoding: utf8
    when: D
loggers:
#  main.core:
#    level: DEBUG
#    handlers: [console, file, error]
  my_moudle:
    level: ERROR
    handlers: [error]


root:
  level: INFO
  handlers: [file,error]